wip: ci: add published documentation removal
Update to use a better format with an instruction file telling what
event has run and what to do. This should make it easier to customize
publishings on the backend. Add a new workflow to delete the published
documentation when a PR is closed/merged.

Signed-off-by: Fabio Utzig <fabio.utzig@nordicsemi.no>

diff --git a/.github/workflows/docbuild.yml b/.github/workflows/docbuild.yml
--- a/.github/workflows/docbuild.yml
+++ b/.github/workflows/docbuild.yml
@@ -2,6 +2,10 @@ name: Documentation Build
 
 on:
   pull_request:
+    types: [opened, synchronize, reopened]
+    branches:
+      - master
+  push:
     branches:
       - master
 
@@ -54,47 +58,57 @@ jobs:
           export PATH="$HOME/.local/bin:$PATH"
           mkdir -p _build && cd _build
           cmake -GNinja ../nrf/doc
-          ninja build-all
+          #FIXME: faster build while testing
+          ninja mcuboot
+          #ninja build-all
 
-      - name: Check build warnings
-        working-directory: ncs
-        run: |
-          cd _build
-          if [ -s Kconfig/sphinx.log ]; then
-            errors=$(cat Kconfig/sphinx.log)
-            echo "::error file=Kconfig/sphinx.log::$errors"
-            exit 1
-          fi
-          if [ -s zephyr/doc.warnings ]; then
-            errors=$(cat zephyr/doc.warnings)
-            echo "::error file=zephyr/doc.warnings::$errors"
-            exit 1
-          fi
-          if [ -s mcuboot/sphinx.log ]; then
-            errors=$(cat mcuboot/sphinx.log)
-            echo "::error file=mcuboot/sphinx.log::$errors"
-            exit 1
-          fi
-          if [ -s nrf/doc.warnings ]; then
-            errors=$(cat nrf/doc.warnings)
-            echo "::error file=nrf/doc.warnings::$errors"
-            exit 1
-          fi
-          if [ -s nrfxlib/doc.log ]; then
-            errors=$(cat nrfxlib/doc.log)
-            echo "::error file=nrfxlib/doc.log::$errors"
-            exit 1
-          fi
+      #- name: Check build warnings
+      #  working-directory: ncs
+      #  run: |
+      #    cd _build
+      #    if [ -s Kconfig/sphinx.log ]; then
+      #      errors=$(cat Kconfig/sphinx.log)
+      #      echo "::error file=Kconfig/sphinx.log::$errors"
+      #      exit 1
+      #    fi
+      #    if [ -s zephyr/doc.warnings ]; then
+      #      errors=$(cat zephyr/doc.warnings)
+      #      echo "::error file=zephyr/doc.warnings::$errors"
+      #      exit 1
+      #    fi
+      #    if [ -s mcuboot/sphinx.log ]; then
+      #      errors=$(cat mcuboot/sphinx.log)
+      #      echo "::error file=mcuboot/sphinx.log::$errors"
+      #      exit 1
+      #    fi
+      #    if [ -s nrf/doc.warnings ]; then
+      #      errors=$(cat nrf/doc.warnings)
+      #      echo "::error file=nrf/doc.warnings::$errors"
+      #      exit 1
+      #    fi
+      #    if [ -s nrfxlib/doc.log ]; then
+      #      errors=$(cat nrfxlib/doc.log)
+      #      echo "::error file=nrfxlib/doc.log::$errors"
+      #      exit 1
+      #    fi
 
       - name: Archive documentation
         working-directory: ncs/_build
         run: |
-          # FIXME: must be updated once push (master) is added to events
-          mkdir pr && cd pr
-          tar -C ../html -zcf doc_build_pr-${{ github.event.number }}.tar.gz .
+          mkdir doc && cd doc
+          file="doc_build_${GITHUB_RUN_ID}.tgz"
+          tar -C ../html -zcf $file .
+          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+            echo "publish PR-${{ github.event.number }} $file" > event_$GITHUB_RUN_ID.txt
+            echo "${{ github.event.number }}" > pr.txt
+          else
+            # basename will work for both branches and tags
+            branch=$(basename "${{ github.ref }}")
+            echo "publish ${branch} $file" > event_$GITHUB_RUN_ID.txt
+          fi
 
       - name: Upload artifact
         uses: actions/upload-artifact@v2
         with:
-          name: pr
-          path: ncs/_build/pr/
+          name: doc
+          path: ncs/_build/doc
